/*
###############################################################
#  Generated by:      Cadence Encounter 10.11-s096_1
#  OS:                Linux x86_64(Host ID dfm.ee.ucla.edu)
#  Generated on:      Fri Apr 13 14:06:55 2012
#  Design:            s1196_bench
#  Command:           saveNetlist -excludeLeafCell s1196_postrouting.v
###############################################################
*/
// Generated by Cadence Encounter(R) RTL Compiler v10.10-s209_1
// Verification Directory fv/s1196_bench 
module s1196_bench (
	blif_clk_net, 
	blif_reset_net, 
	G0, 
	G1, 
	G2, 
	G3, 
	G4, 
	G5, 
	G6, 
	G7, 
	G8, 
	G9, 
	G10, 
	G11, 
	G12, 
	G13, 
	G546, 
	G539, 
	G550, 
	G551, 
	G552, 
	G547, 
	G548, 
	G549, 
	G530, 
	G45, 
	G542, 
	G532, 
	G535, 
	G537);
   input blif_clk_net;
   input blif_reset_net;
   input G0;
   input G1;
   input G2;
   input G3;
   input G4;
   input G5;
   input G6;
   input G7;
   input G8;
   input G9;
   input G10;
   input G11;
   input G12;
   input G13;
   output G546;
   output G539;
   output G550;
   output G551;
   output G552;
   output G547;
   output G548;
   output G549;
   output G530;
   output G45;
   output G542;
   output G532;
   output G535;
   output G537;

   // Internal wires
   wire G29;
   wire G30;
   wire G31;
   wire G32;
   wire G33;
   wire G34;
   wire G35;
   wire G37;
   wire G38;
   wire G39;
   wire G40;
   wire G42;
   wire G43;
   wire G44;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_234;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_259;
   wire n_260;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_267;
   wire n_271;
   wire n_282;
   wire n_283;
   wire n_287;

   OAI211_X1 g7772 (.ZN(G551), 
	.C2(n_87), 
	.C1(n_254), 
	.B(n_174), 
	.A(n_271));
   AOI22_X1 g7774 (.ZN(n_271), 
	.B2(n_41), 
	.B1(n_179), 
	.A2(G5), 
	.A1(n_263));
   OAI22_X1 g7776 (.ZN(G537), 
	.B2(n_166), 
	.B1(n_232), 
	.A2(n_195), 
	.A1(n_260));
   DFFR_X1 G41_reg (.RN(n_253), 
	.QN(G546), 
	.Q(UNCONNECTED), 
	.D(n_259), 
	.CK(blif_clk_net));
   OR4_X1 g7773 (.ZN(G549), 
	.A4(n_267), 
	.A3(n_181), 
	.A2(n_262), 
	.A1(n_255));
   OR2_X1 g7775 (.ZN(G550), 
	.A2(n_267), 
	.A1(n_256));
   NAND4_X1 g7777 (.ZN(G532), 
	.A4(n_245), 
	.A3(n_228), 
	.A2(n_264), 
	.A1(n_242));
   NAND4_X1 g7778 (.ZN(G535), 
	.A4(n_227), 
	.A3(n_247), 
	.A2(n_252), 
	.A1(n_264));
   OR3_X1 g7780 (.ZN(n_263), 
	.A3(n_223), 
	.A2(n_262), 
	.A1(n_251));
   OAI22_X1 g7781 (.ZN(G547), 
	.B2(n_85), 
	.B1(n_241), 
	.A2(n_109), 
	.A1(n_240));
   AOI221_X1 g7783 (.ZN(n_260), 
	.C2(n_130), 
	.C1(n_246), 
	.B2(G8), 
	.B1(n_238), 
	.A(n_192));
   AOI221_X1 g7787 (.ZN(n_259), 
	.C2(G34), 
	.C1(n_71), 
	.B2(n_19), 
	.B1(n_239), 
	.A(n_257));
   NOR3_X1 g7779 (.ZN(n_267), 
	.A3(G13), 
	.A2(n_248), 
	.A1(G33));
   OR3_X1 g7788 (.ZN(G542), 
	.A3(n_201), 
	.A2(n_236), 
	.A1(n_257));
   OAI221_X1 g7784 (.ZN(n_256), 
	.C2(n_51), 
	.C1(n_234), 
	.B2(G29), 
	.B1(n_249), 
	.A(n_244));
   OAI221_X1 g7801 (.ZN(n_255), 
	.C2(n_97), 
	.C1(n_254), 
	.B2(n_219), 
	.B1(n_250), 
	.A(n_180));
   DFFR_X1 G45_reg (.RN(n_253), 
	.QN(UNCONNECTED0), 
	.Q(G45), 
	.D(n_230), 
	.CK(blif_clk_net));
   OAI22_X1 g7795 (.ZN(n_252), 
	.B2(n_117), 
	.B1(n_137), 
	.A2(n_224), 
	.A1(n_194));
   OAI33_X1 g7790 (.ZN(n_251), 
	.B3(n_248), 
	.B2(n_107), 
	.B1(n_249), 
	.A3(n_222), 
	.A2(n_212), 
	.A1(n_250));
   NAND3_X1 g7799 (.ZN(n_247), 
	.A3(n_287), 
	.A2(G38), 
	.A1(n_246));
   AOI22_X1 g7800 (.ZN(n_245), 
	.B2(n_140), 
	.B1(n_225), 
	.A2(n_206), 
	.A1(n_221));
   AOI22_X1 g7791 (.ZN(n_244), 
	.B2(n_184), 
	.B1(n_173), 
	.A2(G3), 
	.A1(n_262));
   OAI221_X1 g7798 (.ZN(G539), 
	.C2(n_216), 
	.C1(n_211), 
	.B2(G12), 
	.B1(n_208), 
	.A(n_187));
   NAND4_X1 g7792 (.ZN(n_242), 
	.A4(1'b1), 
	.A3(G6), 
	.A2(n_99), 
	.A1(n_237));
   SDFFR_X1 G33_reg (.SI(n_213), 
	.SE(G12), 
	.RN(n_253), 
	.QN(UNCONNECTED1), 
	.Q(G33), 
	.D(n_165), 
	.CK(blif_clk_net));
   AOI21_X1 g7793 (.ZN(n_257), 
	.B2(n_190), 
	.B1(n_241), 
	.A(n_134));
   AOI211_X1 g7789 (.ZN(n_240), 
	.C2(n_217), 
	.C1(n_239), 
	.B(n_203), 
	.A(n_197));
   AND2_X1 g7802 (.ZN(n_238), 
	.A2(n_79), 
	.A1(n_237));
   AOI21_X1 g7803 (.ZN(n_236), 
	.B2(n_220), 
	.B1(n_72), 
	.A(n_241));
   NOR2_X1 g7804 (.ZN(n_246), 
	.A2(n_78), 
	.A1(n_229));
   OAI222_X1 g7808 (.ZN(G552), 
	.C2(n_102), 
	.C1(n_182), 
	.B2(n_46), 
	.B1(n_234), 
	.A2(G40), 
	.A1(n_231));
   OAI22_X1 g7807 (.ZN(G530), 
	.B2(n_161), 
	.B1(n_231), 
	.A2(n_185), 
	.A1(n_232));
   OAI211_X1 g7794 (.ZN(n_230), 
	.C2(n_169), 
	.C1(n_188), 
	.B(n_232), 
	.A(n_229));
   NAND3_X1 g7796 (.ZN(n_264), 
	.A3(n_18), 
	.A2(n_171), 
	.A1(n_237));
   OR3_X1 g7797 (.ZN(n_228), 
	.A3(n_218), 
	.A2(n_193), 
	.A1(n_250));
   OR3_X1 g7805 (.ZN(n_227), 
	.A3(G3), 
	.A2(G44), 
	.A1(n_232));
   OAI21_X1 g7809 (.ZN(G548), 
	.B2(G42), 
	.B1(n_231), 
	.A(n_204));
   INV_X1 g7810 (.ZN(n_249), 
	.A(n_225));
   NOR2_X1 g7814 (.ZN(n_224), 
	.A2(n_135), 
	.A1(n_232));
   AND3_X1 g7819 (.ZN(n_223), 
	.A3(n_222), 
	.A2(n_178), 
	.A1(n_209));
   OAI221_X1 g7820 (.ZN(n_221), 
	.C2(n_220), 
	.C1(n_215), 
	.B2(n_139), 
	.B1(n_214), 
	.A(n_176));
   NOR3_X1 g7806 (.ZN(n_262), 
	.A3(G0), 
	.A2(n_219), 
	.A1(n_231));
   NOR2_X1 g7811 (.ZN(n_225), 
	.A2(n_218), 
	.A1(n_231));
   OR2_X1 g7812 (.ZN(n_241), 
	.A2(n_217), 
	.A1(n_231));
   NAND2_X1 g7813 (.ZN(n_229), 
	.A2(n_216), 
	.A1(n_210));
   OR2_X1 g7815 (.ZN(n_250), 
	.A2(G3), 
	.A1(n_231));
   NOR2_X1 g7816 (.ZN(n_239), 
	.A2(n_200), 
	.A1(n_231));
   AOI21_X1 g7818 (.ZN(n_237), 
	.B2(n_214), 
	.B1(n_215), 
	.A(G12));
   NAND4_X1 g7817 (.ZN(n_213), 
	.A4(G0), 
	.A3(G1), 
	.A2(n_212), 
	.A1(n_207));
   OR2_X1 g7821 (.ZN(n_232), 
	.A2(G12), 
	.A1(n_214));
   INV_X1 g7822 (.ZN(n_211), 
	.A(n_210));
   INV_X1 g7824 (.ZN(n_209), 
	.A(n_231));
   NAND3_X1 g7830 (.ZN(n_208), 
	.A3(n_205), 
	.A2(n_202), 
	.A1(n_199));
   NOR3_X1 g7823 (.ZN(n_210), 
	.A3(G13), 
	.A2(n_206), 
	.A1(n_207));
   NAND3_X1 g7825 (.ZN(n_231), 
	.A3(G12), 
	.A2(n_205), 
	.A1(n_207));
   AOI22_X1 g7827 (.ZN(n_204), 
	.B2(n_64), 
	.B1(n_203), 
	.A2(G34), 
	.A1(n_61));
   NAND3_X1 g7828 (.ZN(n_214), 
	.A3(n_205), 
	.A2(n_202), 
	.A1(n_198));
   AOI211_X1 g7831 (.ZN(n_207), 
	.C2(n_217), 
	.C1(n_114), 
	.B(n_189), 
	.A(n_157));
   AOI211_X1 g7832 (.ZN(n_201), 
	.C2(G8), 
	.C1(G9), 
	.B(n_196), 
	.A(n_200));
   INV_X1 g7838 (.ZN(n_199), 
	.A(n_198));
   NOR3_X1 g7834 (.ZN(n_197), 
	.A3(G7), 
	.A2(n_191), 
	.A1(n_196));
   OAI221_X1 g7839 (.ZN(n_198), 
	.C2(G2), 
	.C1(n_186), 
	.B2(n_195), 
	.B1(n_177), 
	.A(n_73));
   NOR4_X1 g7826 (.ZN(n_194), 
	.A4(G12), 
	.A3(1'b0), 
	.A2(n_193), 
	.A1(n_215));
   NOR3_X1 g7829 (.ZN(n_192), 
	.A3(G12), 
	.A2(n_124), 
	.A1(n_215));
   AND3_X1 g7833 (.ZN(n_203), 
	.A3(G7), 
	.A2(n_191), 
	.A1(G34));
   NAND2_X1 g7836 (.ZN(n_190), 
	.A2(G8), 
	.A1(G34));
   OAI211_X1 g7837 (.ZN(n_189), 
	.C2(G11), 
	.C1(n_167), 
	.B(n_283), 
	.A(n_159));
   OR2_X1 g7835 (.ZN(n_215), 
	.A2(n_205), 
	.A1(n_188));
   NAND3_X1 g7840 (.ZN(n_187), 
	.A3(n_11), 
	.A2(n_175), 
	.A1(n_188));
   DFFR_X1 G34_reg (.RN(n_253), 
	.QN(n_196), 
	.Q(G34), 
	.D(n_183), 
	.CK(blif_clk_net));
   DFFR_X1 G40_reg (.RN(n_253), 
	.QN(UNCONNECTED2), 
	.Q(G40), 
	.D(n_172), 
	.CK(blif_clk_net));
   AND2_X1 g7858 (.ZN(n_186), 
	.A2(n_136), 
	.A1(n_185));
   AOI22_X1 g7844 (.ZN(n_188), 
	.B2(n_184), 
	.B1(n_129), 
	.A2(n_158), 
	.A1(n_168));
   DFFR_X1 G46_reg (.RN(n_253), 
	.QN(UNCONNECTED3), 
	.Q(n_283), 
	.D(n_170), 
	.CK(blif_clk_net));
   NAND2_X1 g7848 (.ZN(n_183), 
	.A2(n_182), 
	.A1(n_234));
   AOI211_X1 g7850 (.ZN(n_181), 
	.C2(G3), 
	.C1(G4), 
	.B(n_182), 
	.A(n_89));
   NAND3_X1 g7843 (.ZN(n_180), 
	.A3(n_212), 
	.A2(n_178), 
	.A1(n_179));
   NAND2_X1 g7847 (.ZN(n_254), 
	.A2(G1), 
	.A1(n_179));
   AOI21_X1 g7849 (.ZN(n_177), 
	.B2(G3), 
	.B1(n_164), 
	.A(n_132));
   OR3_X1 g7851 (.ZN(n_176), 
	.A3(n_205), 
	.A2(G43), 
	.A1(n_175));
   OR3_X1 g7852 (.ZN(n_174), 
	.A3(n_212), 
	.A2(G39), 
	.A1(n_182));
   NOR2_X1 g7854 (.ZN(n_173), 
	.A2(n_80), 
	.A1(n_182));
   OAI22_X1 g7860 (.ZN(n_172), 
	.B2(G6), 
	.B1(n_149), 
	.A2(n_105), 
	.A1(n_163));
   AOI22_X1 g7863 (.ZN(n_185), 
	.B2(n_138), 
	.B1(n_171), 
	.A2(n_217), 
	.A1(n_162));
   INV_X1 g7855 (.ZN(n_234), 
	.A(n_179));
   AOI222_X1 g7859 (.ZN(n_170), 
	.C2(n_151), 
	.C1(n_154), 
	.B2(n_217), 
	.B1(n_119), 
	.A2(n_68), 
	.A1(n_57));
   NOR2_X1 g7856 (.ZN(n_179), 
	.A2(n_169), 
	.A1(n_175));
   OAI22_X1 g7857 (.ZN(n_168), 
	.B2(G7), 
	.B1(n_106), 
	.A2(n_195), 
	.A1(n_144));
   OR3_X1 g7865 (.ZN(n_182), 
	.A3(G13), 
	.A2(G12), 
	.A1(n_202));
   AOI22_X1 g7866 (.ZN(n_167), 
	.B2(G9), 
	.B1(n_121), 
	.A2(n_33), 
	.A1(n_150));
   AND2_X1 g7870 (.ZN(n_166), 
	.A2(n_75), 
	.A1(n_160));
   OR2_X1 g7871 (.ZN(n_165), 
	.A2(n_91), 
	.A1(n_202));
   NOR3_X1 g7864 (.ZN(n_164), 
	.A3(G4), 
	.A2(G35), 
	.A1(n_52));
   DFFR_X1 G44_reg (.RN(n_253), 
	.QN(UNCONNECTED4), 
	.Q(G44), 
	.D(n_148), 
	.CK(blif_clk_net));
   DFFR_X1 G43_reg (.RN(n_253), 
	.QN(UNCONNECTED5), 
	.Q(G43), 
	.D(n_152), 
	.CK(blif_clk_net));
   INV_X1 g7873 (.ZN(n_163), 
	.A(n_156));
   NOR2_X1 g7880 (.ZN(n_162), 
	.A2(G3), 
	.A1(n_282));
   INV_X1 g7902 (.ZN(n_161), 
	.A(n_146));
   AOI221_X1 g7889 (.ZN(n_160), 
	.C2(n_141), 
	.C1(n_103), 
	.B2(n_147), 
	.B1(n_126), 
	.A(n_125));
   NOR2_X1 g7853 (.ZN(n_216), 
	.A2(n_145), 
	.A1(n_133));
   NAND2_X1 g7861 (.ZN(n_175), 
	.A2(n_153), 
	.A1(n_131));
   AOI222_X1 g7867 (.ZN(n_159), 
	.C2(G3), 
	.C1(n_12), 
	.B2(n_158), 
	.B1(n_142), 
	.A2(n_7), 
	.A1(n_65));
   AOI211_X1 g7872 (.ZN(n_157), 
	.C2(G9), 
	.C1(n_191), 
	.B(n_155), 
	.A(n_115));
   OAI21_X1 g7874 (.ZN(n_156), 
	.B2(n_14), 
	.B1(n_155), 
	.A(G8));
   NAND2_X1 g7876 (.ZN(n_154), 
	.A2(G0), 
	.A1(n_143));
   NAND2_X1 g7881 (.ZN(n_202), 
	.A2(G32), 
	.A1(n_153));
   OAI221_X1 g7882 (.ZN(n_152), 
	.C2(G1), 
	.C1(n_42), 
	.B2(n_151), 
	.B1(n_98), 
	.A(G3));
   OAI21_X1 g7883 (.ZN(n_150), 
	.B2(G8), 
	.B1(n_149), 
	.A(n_155));
   AOI221_X1 g7886 (.ZN(n_148), 
	.C2(n_217), 
	.C1(n_70), 
	.B2(n_147), 
	.B1(n_127), 
	.A(n_74));
   DFFR_X1 G36_reg (.RN(n_253), 
	.QN(n_282), 
	.Q(UNCONNECTED6), 
	.D(n_128), 
	.CK(blif_clk_net));
   OAI22_X1 g7903 (.ZN(n_146), 
	.B2(G0), 
	.B1(n_145), 
	.A2(n_222), 
	.A1(n_112));
   AOI22_X1 g7877 (.ZN(n_144), 
	.B2(G3), 
	.B1(n_123), 
	.A2(n_63), 
	.A1(n_116));
   AOI21_X1 g7884 (.ZN(n_143), 
	.B2(n_47), 
	.B1(n_141), 
	.A(n_142));
   OAI222_X1 g7887 (.ZN(n_140), 
	.C2(G4), 
	.C1(n_95), 
	.B2(n_212), 
	.B1(n_96), 
	.A2(G2), 
	.A1(n_5));
   AOI221_X1 g7888 (.ZN(n_139), 
	.C2(n_248), 
	.C1(n_147), 
	.B2(n_137), 
	.B1(n_138), 
	.A(n_101));
   OR2_X1 g7892 (.ZN(n_136), 
	.A2(n_135), 
	.A1(n_118));
   OAI221_X1 g7901 (.ZN(n_153), 
	.C2(n_200), 
	.C1(n_58), 
	.B2(n_113), 
	.B1(n_120), 
	.A(n_134));
   AOI221_X1 g7862 (.ZN(n_133), 
	.C2(n_184), 
	.C1(n_88), 
	.B2(G0), 
	.B1(n_132), 
	.A(n_110));
   OAI221_X1 g7875 (.ZN(n_131), 
	.C2(n_151), 
	.C1(n_94), 
	.B2(n_67), 
	.B1(n_90), 
	.A(n_108));
   SDFFR_X1 G35_reg (.SI(n_122), 
	.SE(n_217), 
	.RN(n_253), 
	.QN(G35), 
	.Q(UNCONNECTED7), 
	.D(n_171), 
	.CK(blif_clk_net));
   OR2_X1 g7893 (.ZN(n_155), 
	.A2(G31), 
	.A1(n_149));
   OAI21_X1 g7894 (.ZN(n_130), 
	.B2(n_217), 
	.B1(n_83), 
	.A(n_200));
   NOR3_X1 g7898 (.ZN(n_129), 
	.A3(n_145), 
	.A2(n_56), 
	.A1(n_100));
   OR2_X1 g7906 (.ZN(n_128), 
	.A2(n_126), 
	.A1(n_127));
   INV_X1 g7907 (.ZN(n_125), 
	.A(n_124));
   SDFFR_X1 G42_reg (.SI(n_44), 
	.SE(n_217), 
	.RN(n_253), 
	.QN(UNCONNECTED8), 
	.Q(G42), 
	.D(n_66), 
	.CK(blif_clk_net));
   DFFR_X1 G32_reg (.RN(n_253), 
	.QN(UNCONNECTED9), 
	.Q(G32), 
	.D(n_92), 
	.CK(blif_clk_net));
   AND4_X1 g7895 (.ZN(n_123), 
	.A4(G11), 
	.A3(n_151), 
	.A2(n_147), 
	.A1(n_122));
   AOI211_X1 g7897 (.ZN(n_142), 
	.C2(G2), 
	.C1(n_111), 
	.B(n_141), 
	.A(G3));
   OAI21_X1 g7899 (.ZN(n_121), 
	.B2(G31), 
	.B1(n_120), 
	.A(n_76));
   NAND2_X1 g7908 (.ZN(n_124), 
	.A2(n_104), 
	.A1(n_171));
   OAI21_X1 g7909 (.ZN(n_119), 
	.B2(G10), 
	.B1(G30), 
	.A(G7));
   AOI21_X1 g7919 (.ZN(n_118), 
	.B2(n_84), 
	.B1(n_117), 
	.A(n_171));
   OAI22_X1 g7924 (.ZN(n_116), 
	.B2(n_115), 
	.B1(n_77), 
	.A2(G7), 
	.A1(n_220));
   AND2_X1 g7931 (.ZN(n_114), 
	.A2(G11), 
	.A1(n_113));
   AOI221_X1 g7936 (.ZN(n_112), 
	.C2(n_212), 
	.C1(n_184), 
	.B2(n_158), 
	.B1(n_8), 
	.A(n_111));
   AND4_X1 g7885 (.ZN(n_110), 
	.A4(n_218), 
	.A3(n_109), 
	.A2(n_248), 
	.A1(n_54));
   DFFR_X1 G39_reg (.RN(n_253), 
	.QN(G39), 
	.Q(UNCONNECTED10), 
	.D(n_60), 
	.CK(blif_clk_net));
   AOI22_X1 g7911 (.ZN(n_108), 
	.B2(n_178), 
	.B1(n_24), 
	.A2(n_107), 
	.A1(n_37));
   AND3_X1 g7916 (.ZN(n_149), 
	.A3(G7), 
	.A2(n_217), 
	.A1(G30));
   NAND3_X1 g7918 (.ZN(n_106), 
	.A3(n_48), 
	.A2(n_104), 
	.A1(n_105));
   AND3_X1 g7921 (.ZN(n_132), 
	.A3(n_45), 
	.A2(n_184), 
	.A1(n_103));
   AOI221_X1 g7923 (.ZN(n_102), 
	.C2(n_193), 
	.C1(n_93), 
	.B2(G2), 
	.B1(n_86), 
	.A(n_38));
   AND2_X1 g7930 (.ZN(n_127), 
	.A2(n_158), 
	.A1(n_103));
   NOR2_X1 g7934 (.ZN(n_101), 
	.A2(n_62), 
	.A1(n_220));
   NOR2_X1 g7935 (.ZN(n_100), 
	.A2(n_103), 
	.A1(n_99));
   INV_X1 g7937 (.ZN(n_98), 
	.A(n_82));
   AOI21_X1 g7896 (.ZN(n_97), 
	.B2(G5), 
	.B1(n_32), 
	.A(n_36));
   DFFR_X1 G29_reg (.RN(n_253), 
	.QN(UNCONNECTED11), 
	.Q(G29), 
	.D(n_49), 
	.CK(blif_clk_net));
   AOI21_X1 g7910 (.ZN(n_96), 
	.B2(G2), 
	.B1(n_95), 
	.A(n_34));
   AOI221_X1 g7912 (.ZN(n_94), 
	.C2(G5), 
	.C1(n_147), 
	.B2(G3), 
	.B1(n_81), 
	.A(n_93));
   OAI221_X1 g7913 (.ZN(n_92), 
	.C2(n_89), 
	.C1(n_104), 
	.B2(n_40), 
	.B1(n_90), 
	.A(n_91));
   NOR3_X1 g7900 (.ZN(n_88), 
	.A3(n_115), 
	.A2(G37), 
	.A1(n_20));
   AOI211_X1 g7917 (.ZN(n_87), 
	.C2(n_158), 
	.C1(n_93), 
	.B(n_141), 
	.A(n_86));
   AOI221_X1 g7922 (.ZN(n_85), 
	.C2(n_117), 
	.C1(n_120), 
	.B2(n_2), 
	.B1(n_84), 
	.A(n_59));
   NAND2_X1 g7933 (.ZN(n_83), 
	.A2(n_109), 
	.A1(G38));
   AOI211_X1 g7938 (.ZN(n_82), 
	.C2(n_80), 
	.C1(n_141), 
	.B(n_93), 
	.A(n_81));
   OAI21_X1 g7943 (.ZN(n_79), 
	.B2(n_217), 
	.B1(n_77), 
	.A(n_78));
   OAI22_X1 g7948 (.ZN(n_171), 
	.B2(n_109), 
	.B1(n_76), 
	.A2(n_25), 
	.A1(n_77));
   INV_X1 g7914 (.ZN(n_75), 
	.A(n_74));
   NAND3_X1 g7920 (.ZN(n_73), 
	.A3(n_50), 
	.A2(n_104), 
	.A1(n_99));
   DFFR_X1 G31_reg (.RN(n_253), 
	.QN(UNCONNECTED12), 
	.Q(G31), 
	.D(n_30), 
	.CK(blif_clk_net));
   AOI21_X1 g7928 (.ZN(n_72), 
	.B2(n_109), 
	.B1(n_16), 
	.A(n_71));
   NOR2_X1 g7929 (.ZN(n_126), 
	.A2(G10), 
	.A1(n_69));
   NOR2_X1 g7932 (.ZN(n_70), 
	.A2(n_10), 
	.A1(n_69));
   OAI221_X1 g7942 (.ZN(n_68), 
	.C2(n_218), 
	.C1(n_39), 
	.B2(G3), 
	.B1(n_222), 
	.A(n_67));
   AOI22_X1 g7944 (.ZN(n_66), 
	.B2(n_64), 
	.B1(n_200), 
	.A2(n_65), 
	.A1(n_22));
   OAI22_X1 g7947 (.ZN(n_63), 
	.B2(n_95), 
	.B1(n_53), 
	.A2(G1), 
	.A1(n_62));
   OAI22_X1 g7949 (.ZN(n_61), 
	.B2(n_200), 
	.B1(n_27), 
	.A2(n_120), 
	.A1(n_43));
   INV_X1 g7951 (.ZN(n_60), 
	.A(n_35));
   DFFR_X1 G30_reg (.RN(n_253), 
	.QN(n_113), 
	.Q(G30), 
	.D(n_28), 
	.CK(blif_clk_net));
   NAND2_X1 g7959 (.ZN(n_220), 
	.A2(G10), 
	.A1(n_59));
   AND2_X1 g7961 (.ZN(n_103), 
	.A2(n_0), 
	.A1(n_58));
   NOR2_X1 g7963 (.ZN(n_122), 
	.A2(G8), 
	.A1(n_77));
   AND2_X1 g7964 (.ZN(n_105), 
	.A2(n_29), 
	.A1(n_58));
   INV_X1 g7967 (.ZN(n_111), 
	.A(n_57));
   NOR4_X1 g7915 (.ZN(n_74), 
	.A4(n_158), 
	.A3(n_26), 
	.A2(n_56), 
	.A1(n_76));
   NOR3_X1 g7940 (.ZN(n_54), 
	.A3(n_52), 
	.A2(n_53), 
	.A1(n_76));
   AOI22_X1 g7945 (.ZN(n_51), 
	.B2(n_50), 
	.B1(n_219), 
	.A2(n_158), 
	.A1(n_6));
   AOI22_X1 g7946 (.ZN(n_49), 
	.B2(n_47), 
	.B1(n_193), 
	.A2(n_1), 
	.A1(n_48));
   AOI222_X1 g7950 (.ZN(n_46), 
	.C2(n_89), 
	.C1(n_45), 
	.B2(n_9), 
	.B1(n_219), 
	.A2(G6), 
	.A1(n_184));
   DFFR_X1 G38_reg (.RN(n_253), 
	.QN(UNCONNECTED13), 
	.Q(G38), 
	.D(n_21), 
	.CK(blif_clk_net));
   OR2_X1 g7956 (.ZN(n_44), 
	.A2(n_13), 
	.A1(n_43));
   NOR2_X1 g7958 (.ZN(n_42), 
	.A2(n_195), 
	.A1(n_90));
   OR2_X1 g7960 (.ZN(n_135), 
	.A2(n_52), 
	.A1(n_62));
   OAI22_X1 g7965 (.ZN(n_41), 
	.B2(G1), 
	.B1(n_39), 
	.A2(n_219), 
	.A1(n_40));
   AOI22_X1 g7968 (.ZN(n_57), 
	.B2(G5), 
	.B1(n_151), 
	.A2(G4), 
	.A1(n_78));
   OAI22_X1 g7969 (.ZN(n_38), 
	.B2(n_23), 
	.B1(n_193), 
	.A2(n_89), 
	.A1(n_53));
   MUX2_X1 g7972 (.Z(n_37), 
	.S(G6), 
	.B(n_78), 
	.A(G2));
   INV_X1 g7980 (.ZN(n_91), 
	.A(n_36));
   INV_X1 g7986 (.ZN(n_137), 
	.A(n_77));
   HA_X1 g7952 (.S(n_35), 
	.CO(n_34), 
	.B(n_195), 
	.A(n_184));
   NOR2_X1 g7981 (.ZN(n_36), 
	.A2(n_195), 
	.A1(n_193));
   NAND2_X1 g7987 (.ZN(n_77), 
	.A2(G7), 
	.A1(n_33));
   DFFR_X1 G37_reg (.RN(n_253), 
	.QN(G37), 
	.Q(n_287), 
	.D(n_4), 
	.CK(blif_clk_net));
   OR3_X1 g7939 (.ZN(n_32), 
	.A3(n_212), 
	.A2(n_47), 
	.A1(n_86));
   AND3_X1 g7941 (.ZN(n_138), 
	.A3(G5), 
	.A2(G11), 
	.A1(n_86));
   NAND2_X1 g7957 (.ZN(n_69), 
	.A2(n_158), 
	.A1(n_31));
   AND2_X1 g7962 (.ZN(n_99), 
	.A2(n_117), 
	.A1(n_31));
   OAI22_X1 g7966 (.ZN(n_30), 
	.B2(G7), 
	.B1(n_17), 
	.A2(n_29), 
	.A1(n_64));
   NAND2_X1 g7974 (.ZN(n_28), 
	.A2(n_29), 
	.A1(n_27));
   NOR2_X1 g7975 (.ZN(n_58), 
	.A2(n_25), 
	.A1(n_26));
   NOR2_X1 g7982 (.ZN(n_59), 
	.A2(G8), 
	.A1(n_26));
   NAND2_X1 g7984 (.ZN(n_24), 
	.A2(n_23), 
	.A1(n_193));
   NOR2_X1 g7988 (.ZN(n_93), 
	.A2(n_217), 
	.A1(n_40));
   NAND2_X1 g7993 (.ZN(n_22), 
	.A2(n_191), 
	.A1(n_15));
   INV_X1 g7996 (.ZN(n_21), 
	.A(n_20));
   NOR2_X1 g7991 (.ZN(n_81), 
	.A2(n_158), 
	.A1(n_45));
   INV_X1 g7970 (.ZN(n_19), 
	.A(n_3));
   INV_X1 g7977 (.ZN(n_62), 
	.A(n_104));
   NOR2_X1 g7985 (.ZN(n_90), 
	.A2(G5), 
	.A1(n_18));
   OR2_X1 g7979 (.ZN(n_43), 
	.A2(n_17), 
	.A1(n_117));
   NAND2_X1 g7989 (.ZN(n_134), 
	.A2(G7), 
	.A1(n_117));
   NAND2_X1 g7990 (.ZN(n_16), 
	.A2(n_29), 
	.A1(n_15));
   NOR3_X1 g7995 (.ZN(n_14), 
	.A3(G11), 
	.A2(n_109), 
	.A1(n_13));
   NAND3_X1 g7997 (.ZN(n_20), 
	.A3(G7), 
	.A2(n_29), 
	.A1(n_12));
   INV_X1 g8015 (.ZN(n_193), 
	.A(n_141));
   INV_X1 g8000 (.ZN(n_169), 
	.A(n_11));
   INV_X1 g8003 (.ZN(n_27), 
	.A(n_65));
   INV_X1 g8005 (.ZN(n_84), 
	.A(n_120));
   INV_X1 g8008 (.ZN(n_67), 
	.A(n_48));
   INV_X1 g8019 (.ZN(n_33), 
	.A(n_10));
   INV_X1 g8017 (.ZN(n_40), 
	.A(n_47));
   INV_X1 g8025 (.ZN(n_39), 
	.A(n_80));
   INV_X1 g8028 (.ZN(n_23), 
	.A(n_9));
   INV_X1 g8036 (.ZN(n_95), 
	.A(n_8));
   INV_X1 g8034 (.ZN(n_78), 
	.A(n_184));
   NAND2_X1 g7992 (.ZN(n_76), 
	.A2(G10), 
	.A1(n_7));
   NOR2_X1 g7976 (.ZN(n_6), 
	.A2(n_195), 
	.A1(n_219));
   AOI21_X1 g7994 (.ZN(n_71), 
	.B2(G9), 
	.B1(G7), 
	.A(n_191));
   INV_X1 g8010 (.ZN(n_178), 
	.A(n_5));
   INV_X1 g8013 (.ZN(n_53), 
	.A(n_18));
   INV_X1 g8042 (.ZN(n_26), 
	.A(n_64));
   AND2_X1 g7973 (.ZN(n_31), 
	.A2(n_17), 
	.A1(n_7));
   NOR2_X1 g7978 (.ZN(n_104), 
	.A2(n_248), 
	.A1(n_56));
   NOR2_X1 g7983 (.ZN(n_86), 
	.A2(G3), 
	.A1(n_56));
   HA_X1 g7971 (.S(n_4), 
	.CO(n_3), 
	.B(G6), 
	.A(G9));
   MUX2_X1 g7998 (.Z(n_2), 
	.S(G10), 
	.B(G9), 
	.A(G11));
   MUX2_X1 g7999 (.Z(n_1), 
	.S(G4), 
	.B(G3), 
	.A(G5));
   NOR2_X1 g8004 (.ZN(n_65), 
	.A2(G9), 
	.A1(n_17));
   NAND2_X1 g8002 (.ZN(n_52), 
	.A2(G11), 
	.A1(n_158));
   NAND2_X1 g8006 (.ZN(n_120), 
	.A2(G8), 
	.A1(n_13));
   NAND2_X1 g8007 (.ZN(n_15), 
	.A2(G7), 
	.A1(n_25));
   NOR2_X1 g8035 (.ZN(n_184), 
	.A2(n_248), 
	.A1(n_158));
   NAND2_X1 g8011 (.ZN(n_5), 
	.A2(G1), 
	.A1(n_248));
   INV_X1 g8021 (.ZN(n_45), 
	.A(n_56));
   NOR2_X1 g8016 (.ZN(n_141), 
	.A2(G5), 
	.A1(n_212));
   NOR2_X1 g8009 (.ZN(n_48), 
	.A2(G1), 
	.A1(n_195));
   INV_X1 g8040 (.ZN(n_0), 
	.A(n_200));
   NOR2_X1 g8014 (.ZN(n_18), 
	.A2(G4), 
	.A1(n_217));
   NOR2_X1 g8001 (.ZN(n_11), 
	.A2(G12), 
	.A1(n_205));
   NAND2_X1 g8020 (.ZN(n_10), 
	.A2(n_109), 
	.A1(n_29));
   INV_X1 g8030 (.ZN(n_107), 
	.A(n_219));
   NOR2_X1 g8012 (.ZN(n_117), 
	.A2(G10), 
	.A1(n_109));
   NOR2_X1 g8029 (.ZN(n_9), 
	.A2(n_195), 
	.A1(n_217));
   NOR2_X1 g8037 (.ZN(n_8), 
	.A2(n_151), 
	.A1(n_248));
   NOR2_X1 g8043 (.ZN(n_64), 
	.A2(n_109), 
	.A1(n_17));
   INV_X1 g8023 (.ZN(n_50), 
	.A(n_89));
   NOR2_X1 g8026 (.ZN(n_80), 
	.A2(n_195), 
	.A1(n_212));
   NOR2_X1 g8018 (.ZN(n_47), 
	.A2(G2), 
	.A1(n_248));
   NAND2_X1 g8041 (.ZN(n_200), 
	.A2(G7), 
	.A1(G10));
   NAND2_X1 g8024 (.ZN(n_89), 
	.A2(G5), 
	.A1(G2));
   NAND2_X1 g8022 (.ZN(n_56), 
	.A2(G4), 
	.A1(G6));
   NAND2_X1 g8033 (.ZN(n_145), 
	.A2(G2), 
	.A1(G1));
   NAND2_X1 g8038 (.ZN(n_115), 
	.A2(G11), 
	.A1(G8));
   NOR2_X1 g8027 (.ZN(n_147), 
	.A2(G4), 
	.A1(G6));
   NAND2_X1 g8039 (.ZN(n_222), 
	.A2(G2), 
	.A1(G0));
   NOR2_X1 g8044 (.ZN(n_7), 
	.A2(G7), 
	.A1(G8));
   NAND2_X1 g8045 (.ZN(n_191), 
	.A2(G8), 
	.A1(G10));
   NAND2_X1 g8031 (.ZN(n_219), 
	.A2(G4), 
	.A1(G1));
   NOR2_X1 g8032 (.ZN(n_12), 
	.A2(G0), 
	.A1(G4));
   INV_X1 g8060 (.ZN(n_13), 
	.A(G7));
   INV_X1 g8057 (.ZN(n_205), 
	.A(G13));
   INV_X1 g8051 (.ZN(n_206), 
	.A(G12));
   INV_X1 g8053 (.ZN(n_248), 
	.A(G3));
   INV_X1 g8048 (.ZN(n_217), 
	.A(G6));
   INV_X1 g8056 (.ZN(n_151), 
	.A(G1));
   INV_X1 g8058 (.ZN(n_25), 
	.A(G8));
   INV_X1 g8052 (.ZN(n_195), 
	.A(G2));
   INV_X1 g8047 (.ZN(n_218), 
	.A(G0));
   INV_X1 g8059 (.ZN(n_253), 
	.A(blif_reset_net));
   INV_X1 g8055 (.ZN(n_212), 
	.A(G4));
   INV_X1 g8050 (.ZN(n_29), 
	.A(G10));
   INV_X1 g8049 (.ZN(n_109), 
	.A(G9));
   INV_X1 g8046 (.ZN(n_158), 
	.A(G5));
   INV_X1 g8054 (.ZN(n_17), 
	.A(G11));
endmodule

