#!/bin/csh
# Last updated 01/15/2026 for EE 201A Winter 2026
#
# Source this script if you are using csh for EE 201A on eeapps.seas.ucla.edu as follows:
# $ source csh_ee201a_setup

# For Cadence 
# source /w/apps3/Cadence/INNOVUS161/SETUP
#alias innovus "/w/apps3/Cadence/INNOVUS161/bin/innovus"

# Append OpenAccess binaries to executable path
setenv PATH "/w/class.1/ee/ee201o/ee201ota/oa/bin/linux_rhel40_64/opt:{$PATH}"
setenv PATH "/w/class.1/ee/ee201o/ee201ota/oa/bin:{$PATH}"
setenv OA_PLUGIN_PATH /w/class.1/ee/ee201o/ee201ota/oa/data/plugins
# Append OpenAccess libraries to load path
if ($?LD_LIBRARY_PATH == 0) then
	setenv LD_LIBRARY_PATH /w/class.1/ee/ee201o/ee201ota/oa/lib/linux_rhel40_64/opt
else
	setenv LD_LIBRARY_PATH "/w/class.1/ee/ee201o/ee201ota/oa/lib/linux_rhel40_64/opt:{$LD_LIBRARY_PATH}"
endif

# For OpenAccess Makefiles
setenv COMPILER_PATH /usr


# Append standard library locations
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/lib64:/usr/lib:/lib64:/lib

#Adding scons
setenv PATH "/w/class.1/ee/ee201o/ee201ota/scons-2.5.0/bin:{$PATH}"
